version: "3.7"

services:
  postgresd:
    image: postgres:16-alpine
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-passwordpostgres}
      - POSTGRES_DB=${POSTGRES_DB:-dev}
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s
    networks:
      - app_internal

  passkey-migrate:
    image: ghcr.io/teamhanko/hanko:v0.10.0
    volumes:
      - type: bind
        source: ./apps/hanko/config.yml
        target: /etc/config/config.yml
    command: --config /etc/config/config.yml migrate up
    restart: on-failure
    depends_on:
      postgresd:
        condition: service_healthy
    networks:
      - app_internal

  passkey:
    image: ghcr.io/teamhanko/hanko:v0.10.0
    depends_on:
      passkey-migrate:
        condition: service_completed_successfully
    ports:
      - 8000:8000
      - 8001:8001 # admin api
    volumes:
      - type: bind
        source: ./apps/hanko/config.yml
        target: /etc/config/config.yml
    command: serve --config /etc/config/config.yml all
    environment:
      - PASSWORD_ENABLED
    networks:
      - app_internal
  mail:
    image: axllent/mailpit:latest
    ports:
      - 8025:8025 # Web UI
      - 1025:1025 # SMTP
    networks:
      - app_internal

networks:
  app_internal:
    name: app_internal
    internal: true
