## https://github.com/teamhanko/hanko/blob/main/backend/docs/Config.md
account:
  allow_deletion: true
database:
  database: dev
  dialect: postgres
  host: db
  port: 5432
  user: admin
  password: password
smtp:
  host: "mail"
  port: "1025"
passcode:
  email:
    from_address: no-reply@kazu.dev
secrets:
  keys:
    - secret_keys_does_not_publish
service:
  name: Hanko Authenitcation Service
webauthn:
  relying_party:
    origins:
      - http://localhost:3000 # backend
session:
  cookie:
    secure: false # is needed for safari, because safari does not store secure cookies on localhost
  enable_auth_token_header: true
server:
  public:
    cors:
      allow_origins:
        - http://localhost:3000

